### ISSUE TITLE
Move build-packages logic into strato binary

### ISSUE THREAD

**Issue by joshwget** [rancher/strato#16]
Create a new `strato build` command to accomplish this.

Some thoughts on the UX around this. `strato build` should be able to

1. Take in a simple Dockerfile and produce a single package.
2. Take in a Dockerfile and a strato.yml and produce one or more packages (in the case of subpackages).
3. Take in a directory similar to the [this](https://github.com/rancher/strato/tree/master/packages) and produce all packages and an `index.yml`. Some of the webserver logic from #17 should probably be handled automatically by this command to make things easier.

**Comment by SvenDowideit** [comment]
doing it now :)

**Comment by joshwget** [comment]
I started some work on it [here](https://github.com/joshwget/strato/tree/refactoring) but it's pretty early stuff so you might be better just starting from scratch.

**Comment by joshwget** [comment]
A few minor things left on this but generally fixed by #18 and #28
